// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/十一页行 copy 2.vue')['default']
    '按钮': typeof import('./src/components/按钮.vue')['default']
    '菜单': typeof import('./src/components/菜单.vue')['default']
    '菜单客服': typeof import('./src/components/菜单客服.vue')['default']
    '菜单助理': typeof import('./src/components/菜单助理.vue')['default']
    '底部': typeof import('./src/components/底部.vue')['default']
    '订单行': typeof import('./src/components/订单行.vue')['default']
    '订单行-测试版': typeof import('./src/components/订单行-测试版.vue')['default']
    '订单行-打印附加页': typeof import('./src/components/订单行-打印附加页.vue')['default']
    '镜片行': typeof import('./src/components/镜片行.vue')['default']
    '镜片行V2': typeof import('./src/components/镜片行V2.vue')['default']
    '利润行': typeof import('./src/components/利润行.vue')['default']
    '十一页行 copy 2': typeof import('./src/components/十一页行 copy 2.vue')['default']
    '首行': typeof import('./src/components/首行.vue')['default']
    '添加订单窗口': typeof import('./src/components/添加订单窗口.vue')['default']
    '条形码': typeof import('./src/components/条形码.vue')['default']
    '头部': typeof import('./src/components/头部.vue')['default']
    '新版按钮': typeof import('./src/components/新版按钮.vue')['default']
    '行': typeof import('./src/components/行.vue')['default']
    '用户行': typeof import('./src/components/用户行.vue')['default']
    '用户行V2': typeof import('./src/components/用户行V2.vue')['default']
    copy: typeof import('./src/components/订单行 copy.vue')['default']
    Icon: typeof import('./src/components/icons/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
